### ISSUE TITLE
Modal Analysis weird results

### ISSUE THREAD

**Issue by TakTakeo** [alfredogneto/GIRAFFE#6]
The results for modal analysis are weird for the new version. All modes are null when in previous versions of GIRAFFE, the results are as follows

[solution_2_eigenvalues_correct.txt](https://github.com/user-attachments/files/17017334/solution_2_eigenvalues_correct.txt)
[solution_2_eigenvalues.txt](https://github.com/user-attachments/files/17017336/solution_2_eigenvalues.txt)
[input.inp.txt](https://github.com/user-attachments/files/17017353/input.inp.txt)

**Comment by alfredogneto** [comment]
Hello, I have solved the input file with the provided version and got reasonable results (attached file). Therefore, it seems that the error should be related to some compiling or another issue. 
[solution_2_eigenvalues.txt](https://github.com/user-attachments/files/17043739/solution_2_eigenvalues.txt)
